module.exports = {
    name: 'ModelEngine',
    description: 'ModelEngine (R4) renders Blockbench models as fully animated entities in Minecraft, built out of item-display bones with real hitboxes, mounts and animation blending. Its API lets a plugin attach a model to any entity (or to a server-less Dummy), play/stop named animations, scale it, control bones, and drive custom mobs, bosses, vehicles and pets that look nothing like vanilla.',
    pluginId: 'ModelEngine',
    dependencies: `
        A resource pack generated by ModelEngine must be served to clients, or models render as
        plain items. ModelEngine R4 requires Java 17+ and Minecraft 1.19.4+.
    `,
    mavenIntegration: `
        <repositories>
            <repository>
                <id>ticxo-repo</id>
                <url>https://mvn.lumine.io/repository/maven-public/</url>
            </repository>
        </repositories>
        <dependencies>
            <dependency>
                <groupId>com.ticxo.modelengine</groupId>
                <artifactId>ModelEngine</artifactId>
                <version>R4.0.8</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    `,
    usage: `
        /**
         * ModelEngine R4 — com.ticxo.modelengine.api
         *
         * The model of the model:
         *
         *   ModeledEntity   = a wrapper around a BASE entity (a real Bukkit entity, or a Dummy that
         *                     has no server-side entity at all). It owns position, rotation and the
         *                     set of models attached to it.
         *   ActiveModel     = ONE Blockbench model instance attached to a ModeledEntity. This is
         *                     what you animate, scale and recolour. A ModeledEntity can hold several.
         *   AnimationHandler= per-ActiveModel animation state machine (play/stop by name).
         *   ModelBlueprint  = the loaded .bbmodel definition, keyed by its model id.
         *
         * So the flow is always: get/create ModeledEntity -> createActiveModel(id) -> addModel(...).
         */

        plugin.yml:
        \`\`\`
        name: MyMobs
        version: 1.0
        main: com.example.MyMobs
        api-version: '1.20'
        depend: [ModelEngine]
        \`\`\`

        ============================================================================
        ENTRY POINT — ModelEngineAPI (all static)
        ============================================================================
        ModeledEntity createModeledEntity(Entity base)
        ModeledEntity createModeledEntity(Entity base, Consumer<ModeledEntity> beforeInit)
        ModeledEntity createModeledEntity(BaseEntity<?> base)
        ModeledEntity createModeledEntity(BaseEntity<?> base, Consumer<ModeledEntity> beforeInit)
        ModeledEntity getModeledEntity(Entity entity)        // null if that entity has no model
        ModeledEntity getModeledEntity(UUID uuid)
        ModeledEntity getModeledEntity(int entityId)
        ModeledEntity getOrCreateModeledEntity(Entity base)
        ModeledEntity getOrCreateModeledEntity(Entity base, Consumer<ModeledEntity> beforeInit)
        ModeledEntity getOrCreateModeledEntity(UUID uuid, Supplier<BaseEntity<?>> baseSupplier)
        ModeledEntity removeModeledEntity(Entity entity)     // also by UUID / entity id
        boolean isModeledEntity(UUID uuid)

        ActiveModel createActiveModel(String modelId)        // null when the blueprint id is unknown
        ActiveModel createActiveModel(ModelBlueprint blueprint)
        ModelBlueprint getBlueprint(String modelId)          // the loaded .bbmodel, or null

        Registries/handlers (advanced): getNMSHandler(), getEntityHandler(), getNetworkHandler(),
        getInteractionTracker(), getMountPairManager(), getMountControllerTypeRegistry(),
        getAnimationHandlerRegistry(), getAnimationPropertyRegistry(), getUserLimbRegistry(),
        getSkinGeneratorService(), getPivotOverrideRegistry(), getConfigCache()

        ============================================================================
        ATTACH A MODEL TO AN ENTITY — the standard recipe
        ============================================================================
        \`\`\`java
        import com.ticxo.modelengine.api.ModelEngineAPI;
        import com.ticxo.modelengine.api.model.ActiveModel;
        import com.ticxo.modelengine.api.model.ModeledEntity;

        Zombie zombie = world.spawn(loc, Zombie.class);
        zombie.setInvisible(true);            // hide the vanilla mob; the model replaces it

        ModeledEntity modeled = ModelEngineAPI.createModeledEntity(zombie);
        ActiveModel model = ModelEngineAPI.createActiveModel("my_boss");   // the .bbmodel id
        if (model == null) { getLogger().warning("Unknown model id"); return; }

        modeled.addModel(model, true);        // true = also add the model's hitbox/mount setup
        modeled.setBaseEntityVisible(false);  // the cleaner way to hide the base entity
        \`\`\`

        {IMPORTANT} \`createActiveModel\` returns null for an unknown model id — always null-check.
        The id is the blueprint name ModelEngine loaded from your .bbmodel file, not the file path.

        ============================================================================
        ModeledEntity
        ============================================================================
        BaseEntity<?> getBase()                              // the entity this model rides
        Map<String, ActiveModel> getModels()                 // model id -> instance
        Optional<ActiveModel> addModel(ActiveModel model, boolean applyBehaviours)
        Optional<ActiveModel> removeModel(String modelId)
        Optional<ActiveModel> getModel(String modelId)
        void destroy()                                       // tear down every model
        void markRemoved(); void restore()
        boolean isInitialized(); boolean isDestroyed(); boolean tick(); int getTick()
        boolean isBaseEntityVisible(); void setBaseEntityVisible(boolean)   // hide the vanilla mob
        boolean isModelRotationLocked(); void setModelRotationLocked(boolean)
        float getYHeadRot()/getXHeadRot()/getYBodyRot()
        void setYHeadRot(float)/setXHeadRot(float)/setYBodyRot(float)       // interpolated
        void setYHeadRotImmediately(float)/setXHeadRotImmediately(float)/setYBodyRotImmediately(float)
        void setRotationTick(int)
        void markHurt(); int getHurtTick()                   // plays the red damage flash
        boolean isGlowing(); int getGlowColor()
        boolean shouldBeSaved(); void setSaved(boolean)      // persist the model across restarts
        void queuePostInitTask(Runnable)                     // run once the model finished initialising
        AnimationLODHandler getAnimationLodHandler()

        ============================================================================
        ActiveModel
        ============================================================================
        ModeledEntity getModeledEntity(); void setModeledEntity(ModeledEntity)
        ModelBlueprint getBlueprint()
        AnimationHandler getAnimationHandler()               // -> playAnimation / stopAnimation
        ModelRenderer getModelRenderer()
        Map<String, ModelBone> getBones()                    // bone name -> bone
        Vector3fc getScale(); void setScale(double scale)    // scales the whole model
        Vector3fc getHitboxScale(); void setHitboxScale(double)
        boolean isMainHitbox(); void setMainHitbox(boolean)  // which model owns the entity's hitbox
        boolean isHitboxVisible(); void setHitboxVisible(boolean)
        boolean isShadowVisible(); void setShadowVisible(boolean)
        boolean canHurt(); void setCanHurt(boolean)
        void destroy(); boolean isDestroyed(); boolean isRemoved(); void setRemoved(boolean)
        void tick(); void generateModel(); void initializeRenderer()
        void removeBone(String boneId); void forceGenerateBone(String, String, BlueprintBone)
        Optional<PivotOverride> getPivotOverride(); void setPivotOverride(PivotOverride)

        ============================================================================
        ANIMATIONS — AnimationHandler
        ============================================================================
        IAnimationProperty playAnimation(String animationName, double lerpIn, double lerpOut,
                                         double speed, boolean force)
          lerpIn / lerpOut : blend-in and blend-out time in SECONDS (0.2 is a good default)
          speed            : playback multiplier (1 = as authored)
          force            : true restarts the animation even if it is already playing
        boolean playAnimation(IAnimationProperty property, boolean force)
        boolean isPlayingAnimation(String animationName)
        void stopAnimation(String animationName)        // respects the animation's blend-out
        void forceStopAnimation(String animationName)   // cuts immediately
        void forceStopAllAnimations()
        IAnimationProperty getAnimation(String name); Map<String, IAnimationProperty> getAnimations()

        \`\`\`java
        AnimationHandler anim = model.getAnimationHandler();
        anim.playAnimation("idle",   0.2, 0.2, 1.0, false);   // loops if the .bbmodel loops it
        anim.playAnimation("attack", 0.1, 0.1, 1.5, true);    // one-shot, 1.5x speed, restartable
        if (anim.isPlayingAnimation("attack")) { /* ... */ }
        anim.stopAnimation("idle");
        \`\`\`

        {IMPORTANT} Whether an animation loops is defined in the .bbmodel (loop / hold / once), not
        by the API. Queue an idle loop right after attaching the model, and one-shots on top of it —
        ModelEngine blends them by the animation's own priority.

        ============================================================================
        DUMMY — a model with NO server-side entity
        ============================================================================
        A Dummy is a base entity that exists only client-side. Use it for pure decoration, cosmetic
        pets and packet-style effects where you do not want a real mob eating tick budget or being
        hit by other plugins.
        \`\`\`java
        import com.ticxo.modelengine.api.entity.Dummy;

        Dummy<?> dummy = new Dummy<>();
        dummy.setLocation(loc);
        dummy.setRenderRadius(48);

        ModeledEntity modeled = ModelEngineAPI.createModeledEntity(dummy);
        modeled.addModel(ModelEngineAPI.createActiveModel("statue"), true);

        // Move it yourself each tick:
        dummy.setLocation(newLocation);
        // Remove it:
        modeled.destroy();
        \`\`\`
        Dummy: Dummy(); Dummy(T original); Dummy(UUID uuid, T original); Dummy(int id, UUID, T)
          boolean isAlive(); UUID getUUID(); void setLocation(Location); float getYRot();
          int getRenderRadius(); void setRenderRadius(int); float getHealth()/getMaxHealth()

        BaseEntity<T>: T getOriginal(); boolean isAlive(); int getEntityId(); Location getLocation()

        ============================================================================
        BONES
        ============================================================================
        \`\`\`java
        ModelBone bone = model.getBones().get("head");
        // Bones expose their own transform/behaviour; the common uses are:
        //  - locating a bone to spawn particles at its world position
        //  - attaching items/blocks through bone behaviours defined in the .bbmodel
        //  - hiding/showing parts of a model
        \`\`\`
        A bone named \`hitbox\` in the .bbmodel defines the model's main hitbox — that is what other
        plugins' click/damage detection sees, and its entity id is the one that arrives in interaction
        packets. Models with no hitbox bone are not clickable.
        Bones named \`mount\` / \`seat\` / \`driver\` set up ModelEngine's mount system.

        ============================================================================
        MOUNTS
        ============================================================================
        \`\`\`java
        // Mount a player on a model that has a mount bone (a vehicle/dragon model):
        modeled.getMountManager().ifPresent(mount -> mount.mountDriver(player));
        // Controller types come from getMountControllerTypeRegistry(); the built-ins are
        // walking / flying / and "none" (rider has no control).
        \`\`\`
        Mount behaviour is configured in the .bbmodel bone naming plus the model config; the API is
        mainly used to seat and eject riders.

        ============================================================================
        PRACTICAL NOTES
        ============================================================================
        - Everything here must run on the MAIN THREAD. ModelEngine ticks with the server and its
          renderer touches entity trackers; calling it async causes ConcurrentModification crashes.
        - The client only sees a model if it has the generated RESOURCE PACK. Without it, models
          render as plain item displays or nothing at all. That is a server setup issue, not an API
          one — but it is the number-one "my model is invisible" cause.
        - Model ids are case-sensitive and come from the .bbmodel file loaded at startup. Use
          \`/meg list\` in-game to see the ids the server actually loaded.
        - Always \`destroy()\` a ModeledEntity you created for a Dummy. Real-entity models are cleaned
          up when the entity dies, but Dummies have nothing to garbage-collect them.
        - setBaseEntityVisible(false) is preferable to entity.setInvisible(true): it also suppresses
          the vanilla nameplate/equipment rendering that otherwise floats inside your model.
        - R4 (this API) is not source-compatible with R3. Older tutorials using
          \`ModelEngineAPI.getModeledEntity(entity).addActiveModel(...)\` are R3 and will not compile.
        - MythicMobs integrates with ModelEngine through the \`model{mid=...}\` mechanic; if you are
          reading a MythicMobs definition, that mechanic is where the model id lives.
        - For heavy use (dozens of models), watch the animation LOD settings — \`getAnimationLodHandler()\`
          on the ModeledEntity controls how far away animations stop being computed.
    `
};
